
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD MUL NUM PA PF SUB\nS : Exp\n\nExp : Exp ADD Exp\n\nExp : Exp SUB Exp\n\nExp : Exp MUL Exp\n\nExp : NUM\n\nExp : PA Exp PF\n'
    
_lr_action_items = {'NUM':([0,4,5,6,7,],[3,3,3,3,3,]),'PA':([0,4,5,6,7,],[4,4,4,4,4,]),'$end':([1,2,3,9,10,11,12,],[0,-1,-5,-2,-3,-4,-6,]),'ADD':([2,3,8,9,10,11,12,],[5,-5,5,5,5,5,-6,]),'SUB':([2,3,8,9,10,11,12,],[6,-5,6,6,6,6,-6,]),'MUL':([2,3,8,9,10,11,12,],[7,-5,7,7,7,7,-6,]),'PF':([3,8,9,10,11,12,],[-5,12,-2,-3,-4,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'Exp':([0,4,5,6,7,],[2,8,9,10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> Exp','S',1,'p_global','main.py',7),
  ('Exp -> Exp ADD Exp','Exp',3,'p_exp_add','main.py',13),
  ('Exp -> Exp SUB Exp','Exp',3,'p_exp_sub','main.py',19),
  ('Exp -> Exp MUL Exp','Exp',3,'p_exp_mul','main.py',25),
  ('Exp -> NUM','Exp',1,'p_exp_num','main.py',31),
  ('Exp -> PA Exp PF','Exp',3,'p_exp_paren','main.py',37),
]
